# https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#configuration-options
changelog:
  exclude:
    labels:
      - meta
  categories:
    - title: New features
      labels:
        - enhancement
    - title: Bug fixes
      labels:
        - bug
    - title: Changes
      labels:
        - '*'
      exclude:
        labels:
          - bug